name: anom-detect-kedro

channels:
  - conda-forge

dependencies:
  - python =3.9
  - black >=23.7.0,<24.0.0
  - flake8 >=6.0.0,<7.0.0
  - ipython >=7.31.1,<9.0
  - isort >=5.12.0
  - jupyter >=1.0.0
  - jupyter_client >=5.1,<9.0
  - jupyterlab >=3.0
  - kedro >=0.18.12,<0.19.0
  - kedro-datasets >=1.5.1,<2.0.0
  - kedro-airflow >=0.6.0,<1.0.0
  - kedro-mlflow >=0.11.9,<1.0.0
  - kedro-viz >=6.3.4,<7.0.0
  - matplotlib >=3.4
  - nbstripout >=0.4
  - numpy >=1.22.0
  - pandas >=2.0.0
  - pytest-cov >=4.1.0
  - pytest-mock >=3.11.0
  - pytest >=7.4.0
  - scikit-learn >=1.3.0
  - wheel >=0.40.0
  - mdurl >=0.1.0,<0.2.0
  - smmap >=3.0.1,<6.0.0
  - chardet >=3.0.2
  - python-json-logger >=2.0.1
  - urllib3 >=1.26.7,<2.0.0
  - oauthlib >=3.1.0
  - pyjwt >=1.7.0
  - tabulate >=0.7.7

